runtime: python37
service: default
entrypoint: gunicorn -b :8080 webserver:app
# entrypoint: python webserver.py

network:
  session_affinity: true

env_variables:
  PORT: 8080
  BUCKET_NAME: "staging.sss-cc-gae-310003.appspot.com"
  PROJECT_ID: "sss-cc-gae-310003"

inbound_services:
- warmup

automatic_scaling:
  target_cpu_utilization: 0.7
  min_instances: 1
  max_instances: 3
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 20