runtime: python37
service: default
# entrypoint: gunicorn -b :8080 -k eventlet webserver:app
entrypoint: python webserver.py

network:
  session_affinity: true

env_variables:
  PORT: 8080
  BUCKET_NAME: "shreyapat"
  PROJECT_ID: "research-aggregator"

inbound_services:
- warmup

automatic_scaling:
  target_cpu_utilization: 0.5
  min_instances: 1
  max_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50